### ISSUE TITLE
Image logo no load!

### ISSUE THREAD

**Issue by daljo25** [wontone18/Bagisto-Stripe-Payment-Gateway#2]
The plugin works fine but the stripe logo image does not load. 

Where should I place the svg so that it shows at checkout?

I have pasted an svg in vendor/wontonee/stripe/src/Resources/view/stripe.blade.php but it doesn't work

![Captura de Pantalla 2024-05-31 a las 11 48 44 a  m](https://github.com/wontone18/Bagisto-Stripe-Payment-Gateway/assets/7244602/5467d9ec-e72b-4ca2-9f6f-5bb64745dc53)

**Comment by wontone18** [comment]
you have to wait for its updated version. In the updated version you can able to upload logo from the admin side. i will update it tomorrow.

**Comment by daljo25** [comment]
Another thing, in the new version it will have a field for public and private keys?

Sorry if the answer is obvious but I'm a junior.

**Comment by daljo25** [comment]
Another thing, in the new version it will have a field for public and private keys?

Sorry if the answer is obvious but I'm a junior.

**Comment by wontone18** [comment]
its fixed you can download the latest version. You have to upload the logo from your admin.

its already having secret key field thats enough. In stripe we are only having publishable key and secret keys. 

![Screenshot 2024-05-31 at 20-35-19 Checkout](https://github.com/wontone18/Bagisto-Stripe-Payment-Gateway/assets/10259774/fb1da9e4-2b71-4c58-a46a-b0473afaa85e)

**Comment by dumitruciolan** [comment]
The image is still broken because of a mistake in the source code.
In vendor/wontonee/stripe/src/Payment/Stripe.php, line 29 attemps to get "sales.payment_methods.stripe.image".
But in the database, the name of the property is "sales.payment_methods.stripe.logo_image".
In order to fix the problem, change the mentioned line's content to `$url = $this->getConfigData('logo_image');`.
Cheers!

**Comment by wontone18** [comment]
I will check that. A newer version will be released soon. The version you are using is quite old.
